[package]
authors = ["Kurtis Dinelle <kurtisdinelle@gmail.com>"]
edition = "2021"
name = "demos"
version = "0.1.0"

[dependencies]
rustngo-lib = { path = "../rustngo-lib" }
#panic-probe = { version = "0.3.2", features = ["print-defmt"] }
#defmt = "0.3.7"
#defmt-rtt = "0.4.1"
